import {
  Baby,
  Banknote,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Camera,
  Car,
  Coffee,
  Droplet,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  Hammer,
  Heart,
  HeartPulse,
  Home,
  Landmark,
  Music,
  PawPrint,
  Pill,
  PiggyBank,
  Pizza,
  Plane,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Tag,
  TrainFront,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Ícones disponíveis pras categorias (chave salva no banco → componente). */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  utensils: Utensils,
  pizza: Pizza,
  coffee: Coffee,
  beer: Beer,
  car: Car,
  bus: Bus,
  train: TrainFront,
  bike: Bike,
  fuel: Fuel,
  plane: Plane,
  home: Home,
  sofa: Sofa,
  hammer: Hammer,
  wrench: Wrench,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  dumbbell: Dumbbell,
  scissors: Scissors,
  sparkles: Sparkles,
  gamepad: Gamepad2,
  film: Film,
  music: Music,
  tv: Tv,
  camera: Camera,
  'graduation-cap': GraduationCap,
  book: BookOpen,
  repeat: Repeat,
  smartphone: Smartphone,
  wifi: Wifi,
  zap: Zap,
  droplet: Droplet,
  shirt: Shirt,
  gem: Gem,
  receipt: Receipt,
  landmark: Landmark,
  wallet: Wallet,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  briefcase: Briefcase,
  gift: Gift,
  heart: Heart,
  star: Star,
  baby: Baby,
  paw: PawPrint,
  umbrella: Umbrella,
  tag: Tag,
}

export const CATEGORY_ICON_KEYS = Object.keys(CATEGORY_ICONS)
